apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: redis-cluster-operator
  name: redis-cluster-operator-metrics-service
  namespace: default
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: redis-cluster-operator
