apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: redis-cluster-operator
  name: manager-metrics-service
  namespace: redis-cluster-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: redis-cluster-operator
