namespace: default

namePrefix: redis-cluster-operator-

bases:
- manager-dev.yaml
- ../crd
- ../rbac

patchesStrategicMerge:
  - |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: leader-election-rolebinding
    subjects:
      - kind: ServiceAccount
        name: redis-cluster-operator-manager
        namespace: default
  - |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: proxy-rolebinding
    subjects:
      - kind: ServiceAccount
        name: redis-cluster-operator-manager
        namespace: default
  - |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: manager-rolebinding
    subjects:
      - kind: ServiceAccount
        name: redis-cluster-operator-manager
        namespace: default
