apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    control-plane: redis-cluster-operator
spec:
  selector:
    matchLabels:
      control-plane: redis-cluster-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: redis-cluster-operator
    spec:
      containers:
        - image: chriscmsoft/golang-dev-pod:0.0.2
          name: golang-dev
      serviceAccountName: redis-cluster-operator-manager
