apiVersion: cache.container-solutions.com/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-sample
spec:
  masters: 3
  replicasPerMaster: 1
  config: |
    maxmemory 200mb
    maxmemory-policy allkeys-lru
  podSpec:
    containers:
      - name: redis
        image: redis:5.0
      # UNCOMMENT to add redis exporter for prometheus monitoring
      # - name: redis-exporter
      #   image: oliver006/redis_exporter:latest
      #   ports:
      #       - containerPort: 9121
      #   env:
      #     - name: REDIS_ADDR
      #       value: 'redis://localhost:6379'
