name: Operator Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          # We specifically use 1.17 as Operator SDK does not yet support 1.18
          go-version: 1.17

  test:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download mods
        run: go mod download

      - name: Test
        run: make test

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Images
        uses: docker/build-push-action@v3
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/containersol/redis-cluster-operator:latest

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/containersol/redis-cluster-operator

      - name: Check Tags
        run: echo ${{ steps.meta.outputs.tags }}
